import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Navebar from "@/components/layout/Navebar";
import { Montserrat } from "next/font/google";

const montserrat = Montserrat({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={montserrat.className}>
        <main>
          <Navebar />
          {children}
        </main>
      </body>
    </html>
  );
}
